#!/usr/bin/env python3
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def replace_once(text: str, old: str, new: str, label: str) -> str:
    count = text.count(old)
    if count != 1:
        raise SystemExit(f"{label}: expected one anchor, found {count}")
    return text.replace(old, new, 1)

path = ROOT / "src/html_tokenizer_markup_declarations_v1.cpp"
text = path.read_text(encoding="utf-8")
text = replace_once(
    text,
    '''#include "html_tokenizer_markup_declarations_v1.hpp"\n''',
    '''#include "html_tokenizer_markup_declarations_v1.hpp"\n\n#include "html_tokenizer_utf8_v1.hpp"\n''',
    "UTF-8 helper include",
)
text = replace_once(
    text,
    '''bool ascii_control_parse_error(char value) noexcept {\n    const auto byte = static_cast<unsigned char>(value);\n    return (byte >= 0x01U && byte <= 0x08U) || byte == 0x0BU ||\n        (byte >= 0x0EU && byte <= 0x1FU) || byte == 0x7FU;\n}\n\n''',
    '''bool ascii_control_parse_error(char value) noexcept {\n    const auto byte = static_cast<unsigned char>(value);\n    return (byte >= 0x01U && byte <= 0x08U) || byte == 0x0BU ||\n        (byte >= 0x0EU && byte <= 0x1FU) || byte == 0x7FU;\n}\n\nbool decode_utf8_scalar_value(\n    std::string_view input,\n    std::size_t offset,\n    std::size_t scalar_bytes,\n    std::uint32_t* value) noexcept {\n    if (value == nullptr || scalar_bytes < 2U || scalar_bytes > 4U ||\n        offset > input.size() || scalar_bytes > input.size() - offset) {\n        return false;\n    }\n    const auto first = static_cast<unsigned char>(input[offset]);\n    std::uint32_t scalar = scalar_bytes == 2U\n        ? static_cast<std::uint32_t>(first & 0x1FU)\n        : scalar_bytes == 3U\n            ? static_cast<std::uint32_t>(first & 0x0FU)\n            : static_cast<std::uint32_t>(first & 0x07U);\n    for (std::size_t index = 1U; index < scalar_bytes; ++index) {\n        const auto continuation = static_cast<unsigned char>(input[offset + index]);\n        scalar = (scalar << 6U) |\n            static_cast<std::uint32_t>(continuation & 0x3FU);\n    }\n    *value = scalar;\n    return true;\n}\n\nbool unicode_noncharacter(std::uint32_t scalar) noexcept {\n    return (scalar >= 0xFDD0U && scalar <= 0xFDEFU) ||\n        (scalar <= 0x10FFFFU && (scalar & 0xFFFFU) >= 0xFFFEU);\n}\n\nbool unicode_control_parse_error(std::uint32_t scalar) noexcept {\n    return scalar >= 0x80U && scalar <= 0x9FU;\n}\n\n''',
    "Unicode input-error helpers",
)
old = '''        for (std::size_t cursor = begin; cursor < end; ++cursor) {\n            const char value = input_[cursor];\n            if (value == '\\0') {\n                if (!emit_parse_error(cursor, "unexpected-null-character")) {\n                    return false;\n                }\n                constexpr std::string_view replacement = "\\xEF\\xBF\\xBD";\n                if (replacement.size() > config_.maximum_token_bytes -\n                        std::min(data->size(), config_.maximum_token_bytes)) {\n                    return fail_markup(\n                        error_,\n                        "HTML markup declaration comment token exceeds bounded byte limit");\n                }\n                data->append(replacement.data(), replacement.size());\n                continue;\n            }\n            if (!ascii_byte(value)) {\n                return fail_markup(\n                    error_,\n                    "HTML markup declaration non-ASCII comment authority is not implemented");\n            }\n            if (data->size() >= config_.maximum_token_bytes) {\n                return fail_markup(\n                    error_,\n                    "HTML markup declaration comment token exceeds bounded byte limit");\n            }\n            data->push_back(value);\n        }\n'''
new = '''        std::size_t cursor = begin;\n        while (cursor < end) {\n            const char value = input_[cursor];\n            if (value == '\\0') {\n                if (!emit_parse_error(cursor, "unexpected-null-character")) {\n                    return false;\n                }\n                constexpr std::string_view replacement = "\\xEF\\xBF\\xBD";\n                if (replacement.size() > config_.maximum_token_bytes -\n                        std::min(data->size(), config_.maximum_token_bytes)) {\n                    return fail_markup(\n                        error_,\n                        "HTML markup declaration comment token exceeds bounded byte limit");\n                }\n                data->append(replacement.data(), replacement.size());\n                ++cursor;\n                continue;\n            }\n            if (!ascii_byte(value)) {\n                const std::size_t scalar_bytes =\n                    detail::html_tokenizer_utf8_scalar_bytes_v1(input_, cursor);\n                if (scalar_bytes == 0U || scalar_bytes > end - cursor) {\n                    return fail_markup(\n                        error_,\n                        "HTML markup declaration comment contains invalid UTF-8 scalar encoding");\n                }\n                std::uint32_t scalar = 0U;\n                if (!decode_utf8_scalar_value(\n                        input_, cursor, scalar_bytes, &scalar)) {\n                    return fail_markup(\n                        error_,\n                        "HTML markup declaration comment scalar decoding failed");\n                }\n                if (unicode_control_parse_error(scalar) &&\n                    !emit_parse_error(cursor, "control-character-in-input-stream")) {\n                    return false;\n                }\n                if (unicode_noncharacter(scalar) &&\n                    !emit_parse_error(cursor, "noncharacter-in-input-stream")) {\n                    return false;\n                }\n                if (data->size() > config_.maximum_token_bytes ||\n                    scalar_bytes > config_.maximum_token_bytes - data->size()) {\n                    return fail_markup(\n                        error_,\n                        "HTML markup declaration comment token exceeds bounded byte limit");\n                }\n                data->append(input_.data() + cursor, scalar_bytes);\n                cursor += scalar_bytes;\n                continue;\n            }\n            if (data->size() >= config_.maximum_token_bytes) {\n                return fail_markup(\n                    error_,\n                    "HTML markup declaration comment token exceeds bounded byte limit");\n            }\n            data->push_back(value);\n            ++cursor;\n        }\n'''
text = replace_once(text, old, new, "Unicode comment collector")
old = '''        std::size_t cursor = data_begin;\n        while (cursor < input_.size() && input_[cursor] != '>') {\n            if (input_[cursor] == '\\0') {\n                return fail_markup(\n                    error_,\n                    "HTML markup declaration input preprocessing/NUL replacement is not implemented");\n            }\n            if (!ascii_byte(input_[cursor])) {\n                return fail_markup(\n                    error_,\n                    "HTML markup declaration non-ASCII bogus-comment authority is not implemented");\n            }\n            ++cursor;\n        }\n        const std::string_view data = input_.substr(data_begin, cursor - data_begin);\n        if (!emit_comment(data)) {\n            return false;\n        }\n'''
new = '''        std::size_t cursor = data_begin;\n        while (cursor < input_.size() && input_[cursor] != '>') {\n            if (input_[cursor] == '\\0') {\n                return fail_markup(\n                    error_,\n                    "HTML markup declaration input preprocessing/NUL replacement is not implemented");\n            }\n            if (!ascii_byte(input_[cursor])) {\n                const std::size_t scalar_bytes =\n                    detail::html_tokenizer_utf8_scalar_bytes_v1(input_, cursor);\n                if (scalar_bytes == 0U) {\n                    return fail_markup(\n                        error_,\n                        "HTML markup declaration bogus comment contains invalid UTF-8 scalar encoding");\n                }\n                cursor += scalar_bytes;\n                continue;\n            }\n            ++cursor;\n        }\n        std::string data;\n        if (!collect_comment_data(data_begin, cursor, &data) ||\n            !emit_comment_owned(std::move(data))) {\n            return false;\n        }\n'''
text = replace_once(text, old, new, "Unicode bogus-comment collector")
path.write_text(text, encoding="utf-8")
print("applied Unicode comment authority diagnostic")
