#!/usr/bin/env python3
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def replace_once(text: str, old: str, new: str, label: str) -> str:
    count = text.count(old)
    if count != 1:
        raise SystemExit(f"{label}: expected one anchor, found {count}")
    return text.replace(old, new, 1)

path = ROOT / "src/html_tokenizer_token_stream_v1.cpp"
text = path.read_text(encoding="utf-8")
old = '''    bool consume_data_state(std::size_t* cursor) {\n        const char character = input_[*cursor];\n        if (character == '\\0') {\n            return fail_tokenizer(\n                error_,\n                "HTML tokenizer post-text-state Data NUL handling is outside admitted v1 subset");\n        }\n        if (character == '&') {\n            return fail_tokenizer(\n                error_,\n                "HTML tokenizer Data-state character references are outside admitted v1 subset");\n        }\n        if (character != '<') {\n            if (!append_character(character)) {\n                return false;\n            }\n            ++*cursor;\n            return true;\n        }\n        if (*cursor + 2U >= input_.size() ||\n            input_[*cursor + 1U] != '/') {\n            return fail_tokenizer(\n                error_,\n                "HTML tokenizer Data-state start-tag/markup handling is outside admitted v1 subset");\n        }\n\n        std::size_t probe = *cursor + 2U;\n        const std::size_t name_begin = probe;\n        while (probe < input_.size() && tag_name_character(input_[probe])) {\n            ++probe;\n        }\n        if (probe == name_begin) {\n            return fail_tokenizer(\n                error_,\n                "HTML tokenizer Data-state end tag is missing a name");\n        }\n        const std::string name =\n            ascii_lower_copy(input_.substr(name_begin, probe - name_begin));\n        while (probe < input_.size() && ascii_space(input_[probe])) {\n            ++probe;\n        }\n        if (probe == input_.size()) {\n            if (!flush_character() ||\n                !emit_parse_error(input_.size(), "eof-in-tag")) {\n                return false;\n            }\n            *cursor = input_.size();\n            return true;\n        }\n        if (input_[probe] != '>') {\n            return fail_tokenizer(\n                error_,\n                "HTML tokenizer Data-state end-tag trailing syntax is outside admitted v1 subset");\n        }\n        if (!emit_end_tag(name)) {\n            return false;\n        }\n        *cursor = probe + 1U;\n        return true;\n    }\n'''
new = '''    bool consume_data_state(std::size_t* cursor) {\n        if (cursor == nullptr || *cursor > input_.size()) {\n            return fail_tokenizer(\n                error_,\n                "HTML tokenizer post-text Data transition offset is invalid");\n        }\n        if (*cursor == input_.size()) {\n            return flush_character();\n        }\n        if (!flush_character()) {\n            return false;\n        }\n\n        const HtmlTokenizerV1ParseError base =\n            position_error(input_, *cursor, "");\n        OffsetSink translated_sink(sink_, base.line, base.column);\n\n        HtmlTokenizerDataStreamV1Config data_config{};\n        data_config.maximum_input_bytes = config_.maximum_input_bytes;\n        data_config.maximum_token_bytes = config_.maximum_token_bytes;\n        data_config.maximum_attributes = 256U;\n\n        HtmlTokenizerDataStreamV1Stats data_stats{};\n        const bool data_success = tokenize_html_data_stream_v1(\n            input_.substr(*cursor),\n            data_config,\n            &translated_sink,\n            &data_stats,\n            error_);\n        if (!account_data_stats(data_stats, stats_, error_)) {\n            return false;\n        }\n        *cursor = input_.size();\n        return data_success;\n    }\n'''
text = replace_once(text, old, new, "post-text Data canonical delegation")
path.write_text(text, encoding="utf-8")
print("applied post-text Data canonical delegation")
