#!/usr/bin/env python3
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
from typing import Any

SOURCE_SIZE_BYTES = 145897
SOURCE_SHA256 = "d741d877ac77c4194c4ad526b5b4a19aef8dfe411ab840a466891cdbb9f362e6"
SOURCE_ENTRY_COUNT = 2231
UPSTREAM_REPOSITORY = "whatwg/html-build"
UPSTREAM_COMMIT = "283a3531a61106d07d9a7d9fb3e6f3b9bfd33d70"
UPSTREAM_PATH = "entities/out/entities.json"
UPSTREAM_GIT_BLOB = "557170b41f47a13a46ec695561eb5fe76da73bdb"
GENERATED_HEADER = "html_named_character_references_v1.generated.hpp"
GENERATED_PART_COUNT = 8


def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def cpp_escape(value: str) -> str:
    output: list[str] = []
    for character in value:
        code = ord(character)
        if character == "\\":
            output.append("\\\\")
        elif character == '"':
            output.append('\\"')
        elif 0x20 <= code <= 0x7E:
            output.append(character)
        else:
            raise ValueError(f"non-ASCII entity name byte U+{code:04X}")
    return "".join(output)


def load_entries(path: Path) -> list[tuple[str, tuple[int, ...]]]:
    raw = path.read_bytes()
    if len(raw) != SOURCE_SIZE_BYTES:
        raise ValueError(
            f"entities.json size mismatch: {len(raw)} != {SOURCE_SIZE_BYTES}")
    digest = sha256_bytes(raw)
    if digest != SOURCE_SHA256:
        raise ValueError(
            f"entities.json SHA-256 mismatch: {digest} != {SOURCE_SHA256}")

    payload: Any = json.loads(raw.decode("utf-8"))
    if not isinstance(payload, dict):
        raise ValueError("entities.json root must be an object")
    if len(payload) != SOURCE_ENTRY_COUNT:
        raise ValueError(
            f"entities.json entry count mismatch: {len(payload)} != {SOURCE_ENTRY_COUNT}")

    entries: list[tuple[str, tuple[int, ...]]] = []
    for source_name, record in payload.items():
        if not isinstance(source_name, str) or not source_name.startswith("&"):
            raise ValueError("entity key must be an ampersand-prefixed string")
        name = source_name[1:]
        if not name or any(ord(character) >= 0x80 for character in name):
            raise ValueError(f"entity name is not non-empty ASCII: {source_name!r}")
        if not isinstance(record, dict):
            raise ValueError(f"entity record is not an object: {source_name}")
        codepoints = record.get("codepoints")
        characters = record.get("characters")
        if not isinstance(codepoints, list) or not 1 <= len(codepoints) <= 2:
            raise ValueError(f"entity must contain one or two code points: {source_name}")
        if not all(isinstance(value, int) for value in codepoints):
            raise ValueError(f"entity code points must be integers: {source_name}")
        values = tuple(codepoints)
        for value in values:
            if value < 0 or value > 0x10FFFF or 0xD800 <= value <= 0xDFFF:
                raise ValueError(f"entity contains invalid Unicode scalar: {source_name}")
        expected_characters = "".join(chr(value) for value in values)
        if characters != expected_characters:
            raise ValueError(f"entity characters/codepoints disagree: {source_name}")
        entries.append((name, values))

    entries.sort(key=lambda item: item[0])
    if len({name for name, _ in entries}) != len(entries):
        raise ValueError("entity names are not unique")
    return entries


def generated_part_name(index: int) -> str:
    return f"html_named_character_references_v1.generated_part{index}.inc"


def partition_entries(
    entries: list[tuple[str, tuple[int, ...]]],
) -> list[list[tuple[str, tuple[int, ...]]]]:
    result: list[list[tuple[str, tuple[int, ...]]]] = []
    base = len(entries) // GENERATED_PART_COUNT
    extra = len(entries) % GENERATED_PART_COUNT
    cursor = 0
    for index in range(GENERATED_PART_COUNT):
        count = base + (1 if index < extra else 0)
        result.append(entries[cursor : cursor + count])
        cursor += count
    if cursor != len(entries) or any(not part for part in result):
        raise ValueError("generated entity partition is inconsistent")
    return result


def render_part(
    index: int,
    entries: list[tuple[str, tuple[int, ...]]],
) -> str:
    lines = [
        "// Generated by scripts/generate_html_named_character_references_v1.py.",
        f"// Part {index + 1} of {GENERATED_PART_COUNT}; do not edit by hand.",
    ]
    for name, values in entries:
        first = values[0]
        second = values[1] if len(values) == 2 else 0
        lines.append(
            "    {\""
            + cpp_escape(name)
            + f"\", 0x{first:06X}U, 0x{second:06X}U, {len(values)}U}},")
    lines.append("")
    return "\n".join(lines)


def render_header(entries: list[tuple[str, tuple[int, ...]]]) -> str:
    maximum_name_bytes = max(len(name.encode("ascii")) for name, _ in entries)
    legacy_count = sum(1 for name, _ in entries if not name.endswith(";"))
    two_scalar_count = sum(1 for _, values in entries if len(values) == 2)

    lines = [
        "#pragma once",
        "",
        "// Generated by scripts/generate_html_named_character_references_v1.py.",
        "// Do not edit by hand.",
        "",
        "#include <array>",
        "#include <cstddef>",
        "#include <cstdint>",
        "#include <string_view>",
        "",
        "namespace zevryon::massivedoc {",
        "",
        "struct HtmlNamedCharacterReferenceV1GeneratedEntry {",
        "    std::string_view name;",
        "    std::uint32_t first_codepoint;",
        "    std::uint32_t second_codepoint;",
        "    std::uint8_t codepoint_count;",
        "};",
        "",
        f'inline constexpr std::string_view kHtmlNamedCharacterReferenceV1SourceRepository = "{UPSTREAM_REPOSITORY}";',
        f'inline constexpr std::string_view kHtmlNamedCharacterReferenceV1SourceCommit = "{UPSTREAM_COMMIT}";',
        f'inline constexpr std::string_view kHtmlNamedCharacterReferenceV1SourcePath = "{UPSTREAM_PATH}";',
        f'inline constexpr std::string_view kHtmlNamedCharacterReferenceV1SourceGitBlob = "{UPSTREAM_GIT_BLOB}";',
        f'inline constexpr std::string_view kHtmlNamedCharacterReferenceV1SourceSha256 = "{SOURCE_SHA256}";',
        f"inline constexpr std::size_t kHtmlNamedCharacterReferenceV1SourceSizeBytes = {SOURCE_SIZE_BYTES}U;",
        f"inline constexpr std::size_t kHtmlNamedCharacterReferenceV1EntryCount = {len(entries)}U;",
        f"inline constexpr std::size_t kHtmlNamedCharacterReferenceV1LegacyNameCount = {legacy_count}U;",
        f"inline constexpr std::size_t kHtmlNamedCharacterReferenceV1TwoScalarCount = {two_scalar_count}U;",
        f"inline constexpr std::size_t kHtmlNamedCharacterReferenceV1MaximumNameBytes = {maximum_name_bytes}U;",
        "",
        f"inline constexpr std::array<HtmlNamedCharacterReferenceV1GeneratedEntry, {len(entries)}> kHtmlNamedCharacterReferenceV1Entries{{{{",
    ]
    for index in range(GENERATED_PART_COUNT):
        lines.append(f'#include "{generated_part_name(index)}"')
    lines.extend([
        "}};",
        "",
        "} // namespace zevryon::massivedoc",
        "",
    ])
    return "\n".join(lines)


def write_generated_files(
    entries: list[tuple[str, tuple[int, ...]]],
    output_dir: Path,
) -> dict[str, str]:
    output_dir.mkdir(parents=True, exist_ok=True)
    outputs: dict[str, str] = {}

    header = render_header(entries)
    (output_dir / GENERATED_HEADER).write_text(header, encoding="utf-8", newline="\n")
    outputs[GENERATED_HEADER] = sha256_bytes(header.encode("utf-8"))

    for index, part_entries in enumerate(partition_entries(entries)):
        name = generated_part_name(index)
        content = render_part(index, part_entries)
        (output_dir / name).write_text(content, encoding="utf-8", newline="\n")
        outputs[name] = sha256_bytes(content.encode("utf-8"))
    return outputs


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--entities-json", required=True, type=Path)
    parser.add_argument("--output-dir", required=True, type=Path)
    args = parser.parse_args()

    entries = load_entries(args.entities_json)
    outputs = write_generated_files(entries, args.output_dir)
    print(
        json.dumps(
            {
                "entries": len(entries),
                "generated": outputs,
                "source_sha256": SOURCE_SHA256,
            },
            indent=2,
            sort_keys=True,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
