#include "cluster_caret_map.hpp"
#include <algorithm>
#include <limits>
#include <new>
#include <span>
namespace zevryon::text { namespace {
template<class T> void release_vector(std::pmr::vector<T>* v) noexcept { std::pmr::vector<T> empty(v->get_allocator().resource()); v->swap(empty); }
std::pmr::memory_resource* usable_resource(std::pmr::memory_resource* r) noexcept { return r?r:std::pmr::get_default_resource(); }
void clear_error(ClusterCaretMapError* e) noexcept {if(e)*e={};}
bool fail(ClusterCaretMapErrorKind k,std::size_t s,std::size_t g,std::uint32_t c,const char* m,ClusterCaretMapError* e) noexcept {if(e){e->kind=k;e->segment_index=s;e->glyph_index=g;e->cluster_index=c;try{e->message=m;}catch(...){e->message.clear();}}return false;}
bool checked_add(std::uint64_t* value,std::uint64_t add) noexcept {if(*value>std::numeric_limits<std::uint64_t>::max()-add)return false;*value+=add;return true;}
bool same_group(const ClusterGlyphMapEntry& a,const ClusterGlyphMapEntry& b) noexcept {return a.segment_index==b.segment_index&&a.first_glyph==b.first_glyph&&a.glyph_count==b.glyph_count;}
bool publish_group(std::pmr::vector<ClusterGlyphMapEntry>* entries,std::uint32_t segment_index,std::span<const ShapedGlyph> glyphs,std::size_t first_glyph,std::size_t glyph_limit,std::uint32_t first_cluster,std::uint32_t cluster_limit,ShapingDirection direction,ClusterCaretMapStats* stats,ClusterCaretMapError* error) noexcept {
 if(first_glyph>=glyph_limit||glyph_limit>static_cast<std::size_t>(std::numeric_limits<std::uint32_t>::max())||first_cluster>=cluster_limit||static_cast<std::size_t>(cluster_limit)>entries->size()) return fail(ClusterCaretMapErrorKind::ClusterCoverageFailure,segment_index,first_glyph,first_cluster,"glyph group does not describe a valid cluster interval",error);
 std::uint32_t flags=direction==ShapingDirection::RightToLeft?kClusterGlyphMapRightToLeft:0U; bool unsafe=false; bool missing=false;
 for(std::size_t i=first_glyph;i<glyph_limit;++i){const auto& glyph=glyphs[i];if((glyph.flags&kShapedGlyphUnsafeToBreak)!=0U){flags|=kClusterGlyphMapUnsafeToBreak;unsafe=true;}if((glyph.flags&kShapedGlyphUnsafeToConcat)!=0U)flags|=kClusterGlyphMapUnsafeToConcat;if((glyph.flags&kShapedGlyphSafeToInsertTatweel)!=0U)flags|=kClusterGlyphMapSafeToInsertTatweel;if(glyph.glyph_id==0U){flags|=kClusterGlyphMapMissingGlyph;missing=true;}}
 const std::uint32_t cluster_span=cluster_limit-first_cluster;if(cluster_span>1U)flags|=kClusterGlyphMapMergedGroup;const std::size_t glyph_count=glyph_limit-first_glyph;
 const ClusterGlyphMapEntry entry{segment_index,static_cast<std::uint32_t>(first_glyph),static_cast<std::uint32_t>(glyph_count),flags};
 for(std::uint32_t c=first_cluster;c<cluster_limit;++c){auto& dst=(*entries)[static_cast<std::size_t>(c)];if(dst.segment_index!=kInvalidClusterMapIndex)return fail(ClusterCaretMapErrorKind::ClusterCoverageFailure,segment_index,first_glyph,c,"two glyph groups overlap the same logical cluster",error);dst=entry;}
 std::uint64_t* direction_groups=direction==ShapingDirection::LeftToRight?&stats->left_to_right_groups:&stats->right_to_left_groups;
 if(!checked_add(&stats->glyph_groups,1U)||!checked_add(&stats->clusters_in_merged_groups,cluster_span>1U?cluster_span:0U)||!checked_add(&stats->merged_groups,cluster_span>1U?1U:0U)||!checked_add(&stats->unsafe_groups,unsafe?1U:0U)||!checked_add(&stats->missing_glyph_groups,missing?1U:0U)||!checked_add(direction_groups,1U))return fail(ClusterCaretMapErrorKind::AggregateOverflow,segment_index,first_glyph,first_cluster,"cluster-map statistics overflowed",error);
 stats->maximum_group_glyphs=std::max(stats->maximum_group_glyphs,glyph_count);stats->maximum_group_clusters=std::max(stats->maximum_group_clusters,cluster_span);return true;
}
} // namespace

ClusterCaretMap::ClusterCaretMap(std::pmr::memory_resource* r):clusters(usable_resource(r)){}
std::pmr::memory_resource* ClusterCaretMap::resource() const noexcept{return clusters.get_allocator().resource();}
void ClusterCaretMap::release() noexcept{release_vector(&clusters);}
const char* cluster_caret_map_error_kind_name(ClusterCaretMapErrorKind k) noexcept {switch(k){case ClusterCaretMapErrorKind::None:return "none";case ClusterCaretMapErrorKind::InvalidArgument:return "invalid_argument";case ClusterCaretMapErrorKind::InvalidSegmentTable:return "invalid_segment_table";case ClusterCaretMapErrorKind::InvalidGlyphCluster:return "invalid_glyph_cluster";case ClusterCaretMapErrorKind::InvalidGlyphOrder:return "invalid_glyph_order";case ClusterCaretMapErrorKind::ClusterCoverageFailure:return "cluster_coverage_failure";case ClusterCaretMapErrorKind::MetadataBudgetExceeded:return "metadata_budget_exceeded";case ClusterCaretMapErrorKind::AggregateOverflow:return "aggregate_overflow";}return "invalid";}
bool inspect_caret_boundary(const ClusterCaretMap& map,std::uint32_t boundary_index,CaretBoundaryInfo* output) noexcept {
 if (output == nullptr || static_cast<std::size_t>(boundary_index) > map.clusters.size()) return false;
 *output = {}; output->boundary_index = boundary_index; const std::size_t boundary = static_cast<std::size_t>(boundary_index);
 if(boundary==0U||boundary==map.clusters.size()){output->left_cluster=boundary==0U?kInvalidClusterMapIndex:boundary_index-1U;output->right_cluster=boundary==map.clusters.size()?kInvalidClusterMapIndex:boundary_index;output->flags=kCaretBoundarySafe|kCaretBoundaryTextEdge|kCaretBoundaryRunEdge|kCaretBoundaryGlyphEdge;return true;}
 output->left_cluster=boundary_index-1U;output->right_cluster=boundary_index;const auto& left=map.clusters[boundary-1U];const auto& right=map.clusters[boundary];const bool edge=!same_group(left,right);const bool run_edge=left.segment_index!=right.segment_index;const bool unsafe=(left.flags&kClusterGlyphMapUnsafeToBreak)!=0U||(right.flags&kClusterGlyphMapUnsafeToBreak)!=0U;
 output->flags|=edge?kCaretBoundaryGlyphEdge:kCaretBoundaryInsideMergedGroup;if(run_edge)output->flags|=kCaretBoundaryRunEdge;if(unsafe)output->flags|=kCaretBoundaryUnsafeToBreak;if(edge&&!unsafe)output->flags|=kCaretBoundarySafe;return true;
}
bool build_cluster_caret_map(const ClusterCaretMapRequest& request,ClusterCaretMap* output,ClusterCaretMapStats* stats,ClusterCaretMapError* error) noexcept {
 if (output == nullptr || stats == nullptr || error == nullptr) return false;
 output->release(); *stats = {}; clear_error(error);
 if(request.shaped_text==nullptr)return fail(ClusterCaretMapErrorKind::InvalidArgument,0U,0U,0U,"cluster mapping requires retained multi-run shaping output",error);
 if(request.cluster_count==std::numeric_limits<std::uint32_t>::max())return fail(ClusterCaretMapErrorKind::InvalidArgument,0U,0U,request.cluster_count,"cluster domain leaves no representable terminal caret boundary",error);
 const auto& segments=request.shaped_text->segments;stats->input_segments=static_cast<std::uint64_t>(segments.size());stats->input_clusters=request.cluster_count;
 if(request.cluster_count==0U){if(!segments.empty())return fail(ClusterCaretMapErrorKind::InvalidSegmentTable,0U,0U,0U,"zero clusters require an empty shaped segment table",error);stats->safe_caret_boundaries=1U;return true;}
 if(segments.empty()||segments.size()>static_cast<std::size_t>(std::numeric_limits<std::uint32_t>::max()))return fail(ClusterCaretMapErrorKind::InvalidSegmentTable,0U,0U,0U,"non-empty cluster domains require a bounded shaped segment table",error);
 ClusterCaretMap working(output->resource());try{working.clusters.resize(request.cluster_count);}catch(const std::bad_alloc&){return fail(ClusterCaretMapErrorKind::MetadataBudgetExceeded,0U,0U,0U,"cluster-to-glyph metadata exceeds its hard budget",error);}catch(...){return fail(ClusterCaretMapErrorKind::MetadataBudgetExceeded,0U,0U,0U,"cluster-to-glyph metadata allocation failed",error);}
 std::uint32_t expected_first=0U;
 for(std::size_t si=0U;si<segments.size();++si){const auto& segment=segments[si];const auto& run=segment.glyphs;
  if(run.first_cluster!=expected_first||run.first_cluster!=segment.run.cluster_index||run.cluster_limit<=run.first_cluster||run.cluster_limit>request.cluster_count||run.direction!=segment.run.direction||run.script!=segment.run.script||(run.direction!=ShapingDirection::LeftToRight&&run.direction!=ShapingDirection::RightToLeft)||run.glyphs.empty()||run.glyphs.size()>static_cast<std::size_t>(std::numeric_limits<std::uint32_t>::max()))return fail(ClusterCaretMapErrorKind::InvalidSegmentTable,si,0U,run.first_cluster,"shaped segments must form one contiguous logical cluster domain",error);
  if(!checked_add(&stats->input_glyphs,static_cast<std::uint64_t>(run.glyphs.size())))return fail(ClusterCaretMapErrorKind::AggregateOverflow,si,0U,run.first_cluster,"input glyph count overflows the cluster-map contract",error);
  for(std::size_t gi=0U;gi<run.glyphs.size();++gi){const auto c=run.glyphs[gi].cluster_index;if(c<run.first_cluster||c>=run.cluster_limit)return fail(ClusterCaretMapErrorKind::InvalidGlyphCluster,si,gi,c,"glyph cluster lies outside its retained shaping segment",error);if(gi!=0U){const auto p=run.glyphs[gi-1U].cluster_index;const bool monotone=run.direction==ShapingDirection::LeftToRight?p<=c:p>=c;if(!monotone)return fail(ClusterCaretMapErrorKind::InvalidGlyphOrder,si,gi,c,"glyph clusters violate monotone-grapheme ordering",error);}}
  const std::span<const ShapedGlyph> glyphs{run.glyphs.data(),run.glyphs.size()};std::size_t first_glyph=0U;
  if(run.direction==ShapingDirection::LeftToRight){std::uint32_t expected_group_first=run.first_cluster;while(first_glyph<glyphs.size()){const auto group_first=glyphs[first_glyph].cluster_index;std::size_t glyph_limit=first_glyph+1U;while(glyph_limit<glyphs.size()&&glyphs[glyph_limit].cluster_index==group_first)++glyph_limit;const auto group_limit=glyph_limit<glyphs.size()?glyphs[glyph_limit].cluster_index:run.cluster_limit;if(group_first!=expected_group_first)return fail(ClusterCaretMapErrorKind::ClusterCoverageFailure,si,first_glyph,group_first,"LTR glyph groups leave a logical cluster gap",error);if(!publish_group(&working.clusters,static_cast<std::uint32_t>(si),glyphs,first_glyph,glyph_limit,group_first,group_limit,run.direction,stats,error))return false;expected_group_first=group_limit;first_glyph=glyph_limit;}if(expected_group_first!=run.cluster_limit)return fail(ClusterCaretMapErrorKind::ClusterCoverageFailure,si,run.glyphs.size(),expected_group_first,"LTR glyph groups do not cover the complete run",error);
  } else {std::uint32_t expected_group_limit=run.cluster_limit;while(first_glyph<glyphs.size()){const auto group_first=glyphs[first_glyph].cluster_index;std::size_t glyph_limit=first_glyph+1U;while(glyph_limit<glyphs.size()&&glyphs[glyph_limit].cluster_index==group_first)++glyph_limit;if(!publish_group(&working.clusters,static_cast<std::uint32_t>(si),glyphs,first_glyph,glyph_limit,group_first,expected_group_limit,run.direction,stats,error))return false;expected_group_limit=group_first;first_glyph=glyph_limit;}if(expected_group_limit!=run.first_cluster)return fail(ClusterCaretMapErrorKind::ClusterCoverageFailure,si,run.glyphs.size(),expected_group_limit,"RTL glyph groups do not cover the complete run",error);}
  expected_first=run.cluster_limit;
 }
 if(expected_first!=request.cluster_count)return fail(ClusterCaretMapErrorKind::ClusterCoverageFailure,segments.size(),0U,expected_first,"shaped segments do not cover the requested cluster domain",error);
 for(std::size_t c=0U;c<working.clusters.size();++c)if(working.clusters[c].segment_index==kInvalidClusterMapIndex)return fail(ClusterCaretMapErrorKind::ClusterCoverageFailure,segments.size(),0U,static_cast<std::uint32_t>(c),"one logical cluster has no glyph-group mapping",error);
 const std::size_t boundary_count=static_cast<std::size_t>(request.cluster_count)+1U;for(std::size_t b=0U;b<boundary_count;++b){CaretBoundaryInfo info;if(!inspect_caret_boundary(working,static_cast<std::uint32_t>(b),&info))return fail(ClusterCaretMapErrorKind::ClusterCoverageFailure,segments.size(),0U,static_cast<std::uint32_t>(b),"caret-boundary inspection failed after map construction",error);std::uint64_t* count=(info.flags&kCaretBoundarySafe)!=0U?&stats->safe_caret_boundaries:&stats->unsafe_caret_boundaries;if(!checked_add(count,1U))return fail(ClusterCaretMapErrorKind::AggregateOverflow,segments.size(),0U,static_cast<std::uint32_t>(b),"caret-boundary count overflowed",error);}
 stats->output_entries=static_cast<std::uint64_t>(working.clusters.size());output->clusters.swap(working.clusters);return true;
}
}
