#pragma once

// Generated by scripts/generate_html_named_character_references_v1.py.
// Do not edit by hand.

#include <array>
#include <cstddef>
#include <cstdint>
#include <string_view>

namespace zevryon::massivedoc {

struct HtmlNamedCharacterReferenceV1GeneratedEntry {
    std::string_view name;
    std::uint32_t first_codepoint;
    std::uint32_t second_codepoint;
    std::uint8_t codepoint_count;
};

inline constexpr std::string_view kHtmlNamedCharacterReferenceV1SourceRepository = "whatwg/html-build";
inline constexpr std::string_view kHtmlNamedCharacterReferenceV1SourceCommit = "283a3531a61106d07d9a7d9fb3e6f3b9bfd33d70";
inline constexpr std::string_view kHtmlNamedCharacterReferenceV1SourcePath = "entities/out/entities.json";
inline constexpr std::string_view kHtmlNamedCharacterReferenceV1SourceGitBlob = "557170b41f47a13a46ec695561eb5fe76da73bdb";
inline constexpr std::string_view kHtmlNamedCharacterReferenceV1SourceSha256 = "d741d877ac77c4194c4ad526b5b4a19aef8dfe411ab840a466891cdbb9f362e6";
inline constexpr std::size_t kHtmlNamedCharacterReferenceV1SourceSizeBytes = 145897U;
inline constexpr std::size_t kHtmlNamedCharacterReferenceV1EntryCount = 2231U;
inline constexpr std::size_t kHtmlNamedCharacterReferenceV1LegacyNameCount = 106U;
inline constexpr std::size_t kHtmlNamedCharacterReferenceV1TwoScalarCount = 93U;
inline constexpr std::size_t kHtmlNamedCharacterReferenceV1MaximumNameBytes = 32U;

inline constexpr std::array<HtmlNamedCharacterReferenceV1GeneratedEntry, 2231> kHtmlNamedCharacterReferenceV1Entries{{
#include "html_named_character_references_v1.generated_part0.inc"
#include "html_named_character_references_v1.generated_part1.inc"
#include "html_named_character_references_v1.generated_part2.inc"
#include "html_named_character_references_v1.generated_part3.inc"
#include "html_named_character_references_v1.generated_part4.inc"
#include "html_named_character_references_v1.generated_part5.inc"
#include "html_named_character_references_v1.generated_part6.inc"
#include "html_named_character_references_v1.generated_part7.inc"
}};

} // namespace zevryon::massivedoc
