[package]
name = "zevryon-unicode-ffi"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[lib]
path = "src/lib.rs"
crate-type = ["staticlib", "rlib"]

[dependencies]
zevryon-unicode-abi = { path = "../zevryon-unicode-abi" }
zevryon-unicode-stream = { path = "../zevryon-unicode-stream" }
